---
title: "Chicago Water Shutoffs Exploratory Data"
author: "Emmett McKinney"
date: "3/16/2019"
output: html_document
---

**THIS DOCUMENT JOINS SHUTOFF WITH CENSUS DATA & DOES SOME INITIAL ANALYSIS**

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("/Users/emmettmckinney/Dropbox (MIT)/RAship/ESI_Water_Affordability_031120/Data/WBEZ_Data/Chicago")
```

```{r}
#Install needed packages 

library(dplyr)
library(tidyr)
library(readxl)
library(stargazer)
library(spdep)
library(sf)
library(leaflet)
library(RColorBrewer)
library(rstatix)
library(spatialreg)
library(ggplot2)
```

```{r}
shutoffs <- st_read("/Users/emmettmckinney/Dropbox (MIT)/RAship/ESI_Water_Affordability_031120/Data/WBEZ_Data/Chicago/Data/chicago_zip_year_shutoffs.geojson") %>% drop_na() %>%
  mutate(Maj_Minority = if_else(Prc_NonW > 0.5, "Yes", "No"),
        log_Prc_Blk = log(Prc_Blk), 
        log_MHI = log(MHI)) %>% drop_na() %>% 
  filter(log_Prc_Blk > -1000, log_MHI > - 1000)
```


**Analyze Shutoff Frequency Across Zip Codes - non spatial regression**

*Descriptive Statistics*
```{r}

summary <- shutoffs %>% select(-"geometry") %>%
summarise(
    n = n(),
    mean = mean(shutoffs_1000p),
    max = max(shutoffs_1000p),
    min = min (shutoffs_1000p),
    sd = sd(shutoffs_1000p),
    median = median(shutoffs_1000p),
    Maj_Minority = ("Total")
  ) 

grouped_summary <- shutoffs %>% group_by(Maj_Minority) %>% select(-"geometry") %>% 
summarise(
    n = n(),
    mean = mean(shutoffs_1000p),
    max = max(shutoffs_1000p),
    min = min(shutoffs_1000p),
    sd = sd(shutoffs_1000p),
    median = median(shutoffs_1000p)
  ) 

overall_summary <- grouped_summary %>% rbind(summary)
overall_summary <- data.frame(overall_summary) %>% select(-geometry)
overall_summary
```

```{r}
means <- data.frame(shutoffs) %>% group_by(Maj_Minority) %>% summarize(mean = mean(log_shut))
means

p <- ggplot(shutoffs, aes(x=log_shut, fill = Maj_Minority, color = Maj_Minority)) +
  geom_histogram(position = "identity", alpha = 0.5) + 
  ggtitle("Shutoff Order by Zip Code and Racial Majority, Chicago") +
  xlab("Log of Number of Shutoff Orders") +
  ylab("Number of Zip Codes") +
  scale_fill_discrete(name = "Racial Makeup", labels = c("Majority White", "Majority Non-White")) +
   geom_vline(data=means, aes(xintercept=mean, colour=Maj_Minority), linetype="dashed", size=1, show.legend = TRUE) 

p
```

```{r}
t_test <- shutoffs %>% t_test(shutoffs_1000p ~ Maj_Minority) %>%
  add_significance()
t_test
```

```{r}
pal <- colorBin("Reds", domain = shutoffs$log_shut , bins = 7)
leaflet(st_transform(shutoffs, 4326)) %>% 
setView(-87.6298, 41.8781, 10) %>%
addProviderTiles("Stamen.Toner.Background") %>%
addPolygons(
fillColor = ~pal(log_shut),
weight = 1,
opacity = 1,
color = 'white',
fillOpacity = 0.8
) %>%
addLegend(
pal = pal,
values = ~log_shut,
opacity = 0.8,
title = NULL,
position = "bottomright")
```

```{r}
#Test Response Variable for Autocorrelation
weights <- nb2listw(poly2nb(shutoffs, queen = FALSE), style="W")
shutoffs_moran <- moran.test(shutoffs$log_shut, weights)
print(shutoffs_moran)
moran.plot(shutoffs$log_shut, weights)
```

```{r}
#Standard OLS
formula_1 <- log_shut ~ log_Prc_NonW + log_MHI
ols_1 <- lm(formula = formula_1, data = shutoffs)
summary(ols_1)
plot(ols_1)
```

```{r}
#Check of autocorrelation in residuals of OLSs
shutoffs$ols_resid_1 <- residuals(ols_1)
shutoffs_pal_1 <- colorBin(
  palette = "Spectral",
  domain = c(-max(shutoffs$ols_resid_1), max(shutoffs$ols_resid_1)),
  bins=7)
```

```{r}
leaflet(st_transform(shutoffs,4326)) %>%
  addProviderTiles(providers$Stamen.Toner) %>%
  addPolygons(smoothFactor = 0.2, fillOpacity = 0.8,
              color = "#fff", weight = 1,
              fillColor = ~shutoffs_pal_1(ols_resid_1))%>%
  addLegend(pal= shutoffs_pal_1, values =~ols_resid_1)

moran.plot(shutoffs$ols_resid_1, weights)
moran.test(shutoffs$ols_resid_1, weights)
```


```{r}
#Correct autocorrelation through Lag Model 
lag_1 <- lagsarlm(
  formula = formula_1, 
  data = shutoffs, 
  listw = weights, 
  type = "lag"
  )
```

```{r}
#Check for residual autocorrelation correction
shutoffs$lag_resid_1 <- residuals(lag_1)
shutoffs_pal_1 <- colorBin(
  palette = "Spectral",
  domain = c(-max(shutoffs$lag_resid_1), max(shutoffs$lag_resid_1)),
  bins = 7)

leaflet(st_transform(shutoffs,4326)) %>%
  addProviderTiles(providers$Stamen.TonerBackground) %>%
  addPolygons(smoothFactor = 0.2, fillOpacity = 0.8,
              color = "#fff", weight = 1,
              fillColor = ~shutoffs_pal_1(lag_resid_1))%>%
  addLegend(pal=shutoffs_pal_1, values=~lag_resid_1)

moran.test(shutoffs$lag_resid_1, weights)
moran.plot(shutoffs$lag_resid_1, weights)
```

```{r}
#Impacts
impacts(lag_1, listw=weights)
```

```{r}
err_1 <- errorsarlm(
  formula = formula_1, 
  data = shutoffs, 
  listw = weights
  )

shutoffs$err_resid <- residuals(err_1)
moran.test(shutoffs$err_resid, weights)
```

```{r}
pal <- colorBin("Reds", domain = shutoffs$err_resid, bins = 7)
leaflet(st_transform(shutoffs, 4326)) %>% 
setView(-87.6298, 41.8781, 10) %>%
addProviderTiles("Stamen.Toner.Lite") %>%
addPolygons(
fillColor = ~pal(err_resid),
weight = 1,
opacity = 1,
color = 'white',
fillOpacity = 0.8
) %>%
addLegend(
pal = pal,
values = ~err_resid,
opacity = 0.8,
title = NULL,
position = "bottomright")
```

```{r}
comparison <- AIC(ols_1, err_1, lag_1)

#Conclusion: Spatial Lag model is the best. 
```

```{r, results = "asis"}
#Print results.

#summary

write.csv(overall_summary, file = "/Users/emmettmckinney/Dropbox (MIT)/RAship/ESI_Water_Affordability_031120/Data/WBEZ_Data/Chicago//Results/chicago_summary_stats.csv")

#T-test 
write.csv(t_test, file = "/Users/emmettmckinney/Dropbox (MIT)/RAship/ESI_Water_Affordability_031120/Data/WBEZ_Data/Chicago//Results/chicago_majmin_t_test.csv")

#histogram
ggsave(p, file = "/Users/emmettmckinney/Dropbox (MIT)/RAship/ESI_Water_Affordability_031120/Data/WBEZ_Data/Chicago//Results/chicago_shutoffs__hist.png")

#OLS

stargazer(ols_1, type = "html", title = "OLS Regression - Log Shutoffs  vs. Log % Non-White and Log MHI by Zip Code, Chicago", header = FALSE, covariate.labels = c("% Non-White","Median Household Income"), dep.var.labels = "Log # of Water Shutoffs",  out = "/Users/emmettmckinney/Dropbox (MIT)/RAship/ESI_Water_Affordability_031120/Data/WBEZ_Data/Chicago//Results/chicago_ols_1.html")


#error model

stargazer(err_1, type = "html", title = "Spatial Error Model  - Log Shutoffs  vs. Log % Non-White and Log MHI by Zip Code, Chicago", header = FALSE, covariate.labels = c("% Non-White","Median Household Income"), dep.var.labels = "Log # of Water Shutoffs", out =  "/Users/emmettmckinney/Dropbox (MIT)/RAship/ESI_Water_Affordability_031120/Data/WBEZ_Data/Chicago/Results/chicago_err_1.html")

#Lag model

stargazer(lag_1, type = "html", title = "Spatial lag Model  - Log Shutoffs  vs. Log % Non-White and Log MHI by Zip Code, Chicago", header = FALSE, covariate.labels = c("% Non-White","Median Household Income"), dep.var.labels = "Log # of Water Shutoffs", out =  "/Users/emmettmckinney/Dropbox (MIT)/RAship/ESI_Water_Affordability_031120/Data/WBEZ_Data/Chicago/Results/chicago_lag_1.html")

#AIC table

write.csv(comparison, file = "/Users/emmettmckinney/Dropbox (MIT)/RAship/ESI_Water_Affordability_031120/Data/WBEZ_Data/Chicago/Results/chicago_AIC_comparison.csv")

stargazer(ols_1, lag_1, err_1, type = "html", title = "Combined Spatial Regression Models, Chicago Water Shutoffs", header = FALSE, covariate.labels = c("% Non-White","Median Household Income"), dep.var.labels = "Log # of Water Shutoffs", out =  "/Users/emmettmckinney/Dropbox (MIT)/RAship/ESI_Water_Affordability_031120/Data/WBEZ_Data/Chicago/Results/chicago_combined_1.html")


```



